simplemooc/accounts/urls.py
#from django.urls import path, include
from . import views
from django.conf.urls import include, url
from django.contrib.auth.views import LoginView, LogoutView


app_name='accounts'

urlpatterns = [
        url(r'^$', views.dashboard, name='dashboard'),
        url(r'^entrar/$', LoginView.as_view(), name='login'), 
        url(r'^cadastre-se/$', views.register, name='register'), 
        url(r'^nova-senha/$', views.password_reset, name='password_reset'), 
        url(r'^sair/$', LogoutView.as_view(next_page='core:home'), name='logout'),
        url(r'^editar$', views.edit, name='edit'), 
        url(r'^editar-senha$', views.edit_password, name='edit_password'), 

]               

simplemooc/urls.py
#from django.contrib import admin
#from django.urls import path, include
#from simplemooc.core import urls, views
#from simplemooc.courses import urls, views

from django.contrib import admin
from django.urls import path, include
from simplemooc.core import views, urls
from simplemooc.courses import views, urls
from simplemooc.accounts import views, urls
from django.conf import settings
from django.conf.urls.static import static



#urlpatterns = [
#        path('', include(urls,namespace='core')),
#        path('cursos/', include(urls,namespace='courses')),
#        path('admin/', admin.site.urls),
#]

urlpatterns = [
	path('', include('simplemooc.core.urls', namespace='Core')),
    path('cursos/', include('simplemooc.courses.urls', namespace='Courses')),
    path('conta/', include('simplemooc.accounts.urls', namespace='Accounts')),
  #  path('forum/', include('simplemooc.forum.urls', namespace='Forum')),
	
    path('admin/', admin.site.urls),

] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

simplemooc/accounts/models.py
import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin,
    UserManager)
from django.conf import settings

class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        ("Nome de Usuário"), max_length=30, unique=True,
        validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'), 
            'O mome de usuário só pode contar letras, numeros e os caracteres: @/+/-/]/+/$/', 'invalid')]
        )
    email = models.EmailField(("E-mail"), max_length=254, unique=True)
    name = models.CharField(("Nome"), max_length=100, blank=True)
    is_active = models.BooleanField(("Está ativo?"), blank=True, default=True)
    is_staff = models.BooleanField(("É da equipe?"), blank=True, default=False)
    date_joined = models.DateTimeField(("Data de entrada"), auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

class PasswordReset(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=("Usuário"),
            on_delete=models.CASCADE, 
            related_name='resets'
        )
    
    key = models.CharField(("Chave"), max_length=100, unique=True)
    created_at = models.DateTimeField(("Criado em"), auto_now_add=True)
    confirmed = models.BooleanField(("Confirmado?"), default=False, blank=True)
    
    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova Senha'
        verbose_name_plural = 'Novas Senhas'
        ordering = ['-created_at']
    

simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
#from django.contrib.auth.models import User # import original usando a tabela de user.
from django.contrib.auth import get_user_model

User = get_user_model()

# Classe utilizada para Form com o Model original do Django

# class RegisterForm(UserCreationForm):

#     email = forms.EmailField(label='E-mail', required=False)

#     def clean_email(self):
#         email = self.cleaned_data['email']
#         if User.objects.filter(email=email).exists():
#             raise forms.ValidationError('Já existe usuário com este e-mail')
#         return email

#     def save(self, commit=True):
#         user = super(RegisterForm, self).save(commit=False)
#         user.email = self.cleaned_data['email']
#         if commit: 
#             user.save()
#         return user 

class PasswordResetForm(forms.Form):

    email = forms.EmailField(label='E-mail', required=False)

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError(
            'Nenhum usuário cadastrado com este e-mail'
        )


class RegisterForm(forms.ModelForm):

    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirmação de Senha', widget=forms.PasswordInput
    )

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação não está correta')
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'email']



class EditAccountForm(forms.ModelForm):

    def clean_email(self):
        email = self.cleaned_data['email']
        queryset = User.objects.filter(email=email).exclude(pk=self.instance.pk) 
        if queryset.exists():
            raise forms.ValidationError('Já existe usuário com este e-mail')
        return email
    
    class Meta:
        model = User
        #fields = ('username','email', 'first_name', 'last_name')
        fields = ('username','email')

simplemooc/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .forms import RegisterForm, EditAccountForm, PasswordResetForm
from .models import PasswordReset
from simplemooc.core.utils import generate_hash_key

User = get_user_model()

@login_required
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    return render(request, template_name)

def register(request):
    templete_name = 'accounts/register.html'
    if request.method == 'POST':
        #form = UserCreationForm(request.POST) ***Aula Login inicial usando o forms padrão do user creation form***
        form = RegisterForm(request.POST)
        if form.is_valid():
            #form.save()
            user = form.save()
            user = authenticate(
                username=user.username, password=form.cleaned_data['password1']
                )
            login(request, user)
            return redirect('core:home')
            return redirect(settings.LOGIN_URL)
    else: 
        #form = UserCreationForm() ***Aula Login inicial usando o forms padrão do user creation form***
        form = RegisterForm() # ** Form personalizado 
    context = { 
        'form': form
    }
    return render(request, templete_name, context)

def password_reset(request):
    template_name = 'accounts/password_reset.html'
    context = {}
    form = PasswordResetForm(request.POST or None)
    if form.is_valid():
        user = User.objects.get(email=form.cleaned_data['email'])
        key = generate_hash_key(user.username)
        reset = PasswordReset(user=user, key=key)
        reset.save()
        context['success'] = True
    context['form'] = form
    
    return render(request, template_name, context)

@login_required
def edit(request):
    template_name = 'accounts/edit.html'
    form = EditAccountForm()
    context = {}
    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form .save()
            form = EditAccountForm(instance=request.user)
            context['success'] = True
    else:
        form = EditAccountForm(instance=request.user)
    context['form'] = form
    return render(request, template_name, context)


@login_required
def edit_password(request):
    template_name = 'accounts/edit_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
    else: 
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)

simplemooc/accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <ul class="breadcrumb">
                {% block breadcrumb %}
                <li><a href="{% url 'accounts:dashboard' %}">Meu Painel</a></li>
                {% endblock %}
            </ul>
        </div>
        <div class="pure-u-1-3">
            <div class="pure-menu pure-menu-open">
                <a class="pure-menu-heading">Meus Cursos</a>
                <ul>
                    <li><a href="#">Cursos 1</a></li>
                    <li><a href="#">Cursos 2</a></li>
                    <li class="pure-menu-heading">Minha Conta</li>
                    <li><a href="{% url 'accounts:edit'%}">Editar Conta</a></li>
                    <li><a href="{% url 'accounts:edit_password'%}">Alterar Senha</a></li>
                </ul>
            </div>
        </div>
        <div class="pure-u-2-3">
            <div class="inner">
                {% block dashboard_content %}
                <p><strong>Usuário</strong>: {{ user }} </p>
                <p><strong>E-mail</strong>: {{ user.email }} </p>
                {% endblock  %}
               
            </div>
        </div>
    </div>

{% endblock %}

simplemooc/accounts/templates/accounts/edit.html
{% extends 'accounts/dashboard.html' %}

{% block breadcrumb %}
    {{block.super}}
    <li>/</li>
    <li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
{% endblock  %}
{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>Os dados foram alterados com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Salvar Modificações</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/edit_password.html
{% extends 'accounts/dashboard.html' %}

{% block breadcrumb %}
    {{block.super}}
    <li>/</li>
    <li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
{% endblock  %}
{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>A sua senha foi alterada com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Alterar Senha</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h2>Informe seu E-mail</h2>
            {% if success %}
            <p> Um e-mail foi enviado para você com mais detalhes de como criar uma nova senha.</p>
            {% else %}
            <form class="pure-form pure-form-aligned" method="post">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_field_errors }}

                    {% for field in form %}
                    <div class="pure-control-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}

                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Enviar E-mail</button>
                    </div>
                </fieldset>                
            </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

simplemooc/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h2>Informe seus dados</h2>
            <form class="pure-form pure-form-aligned" method="post">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_field_errors }}

                    {% for field in form %}
                    <div class="pure-control-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}

                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                    </div>
                </fieldset>                
            </form>
        </div>
    </div>
{% endblock %}